### ISSUE TITLE
multiselect and multicheckbox not working

### ISSUE THREAD

**Issue by noplanman** [WPUserManager/wp-optionskit#8]
With `multicheckbox` i get the following console error when checking items, clicking save sends an empty selection:
```
TypeError: this.checkedItems.push is not a function
    at a.onChange (multicheckbox.vue:39:1)
    at qt (vue.esm.js:1872:1)
    at HTMLInputElement.n (vue.esm.js:2197:1)
    at HTMLInputElement.o._wrapper (vue.esm.js:7609:1)
```

With `multiselect` i get the following console error on page load and no input is rendered:
```
vue.esm.js:1906 TypeError: this.options.concat is not a function
    at a.filteredOptions (vue-multiselect.min.js:1:9528)
    at mn.get (vue.esm.js:4504:1)
    at mn.evaluate (vue.esm.js:4606:1)
    at a.filteredOptions (vue.esm.js:4860:1)
    at a.<anonymous> (vue.esm.js:512:1)
    at mn.get (vue.esm.js:4504:1)
    at new mn (vue.esm.js:4493:1)
    at a.t.$watch (vue.esm.js:4970:1)
    at Sn (vue.esm.js:4930:1)
    at vue.esm.js:4909:1
```

**Comment by miriksbm** [comment]
Hey @noplanman 
I'm getting the same error here, however... in version 1.0.15 this seem to be working still.
You have the same thing? 

This project seems to be abandoned, or... at least left broken for some time now.

**Comment by noplanman** [comment]
@miriksbm I'll take a look and see.

Yes, unfortunately it has been abandoned. I've forked it and maybe I'll add / fix some things, not sure yet.
